export enum TalkSubject {
  AI = 'AI',
  WEB_DEVELOPMENT = 'WEB_DEVELOPMENT',
  MOBILE_DEVELOPMENT = 'MOBILE_DEVELOPMENT',
  DATA_SCIENCE = 'DATA_SCIENCE',
  CLOUD_COMPUTING = 'CLOUD_COMPUTING',
  DEVOPS = 'DEVOPS',
  CYBER_SECURITY = 'CYBER_SECURITY',
  BLOCKCHAIN = 'BLOCKCHAIN',
  IOT = 'IOT',
  GAME_DEVELOPMENT = 'GAME_DEVELOPMENT',
}
